kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  name: "myapp"
  labels:
    app: "myapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "myapp"
  template:
    metadata:
      labels:
        app: "myapp"
    spec:
      containers:
        - name: "myapp"
          image: "quay.io/myteam/myapp:master"
          ports:
            - name: "http-server"
              containerPort: 80
          env:
            - name: "KEY1"
              value: "VALUE"
            - name: "KEY2"
              value: "VALUE"
